/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gs.hack.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TimesheetApproval service. Represents a row in the &quot;gw_TimesheetApproval&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.gs.hack.model.impl.TimesheetApprovalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.gs.hack.model.impl.TimesheetApprovalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TimesheetApproval
 * @see com.liferay.gs.hack.model.impl.TimesheetApprovalImpl
 * @see com.liferay.gs.hack.model.impl.TimesheetApprovalModelImpl
 * @generated
 */
@ProviderType
public interface TimesheetApprovalModel extends BaseModel<TimesheetApproval>,
	GroupedModel, ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a timesheet approval model instance should use the {@link TimesheetApproval} interface instead.
	 */

	/**
	 * Returns the primary key of this timesheet approval.
	 *
	 * @return the primary key of this timesheet approval
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this timesheet approval.
	 *
	 * @param primaryKey the primary key of this timesheet approval
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this timesheet approval.
	 *
	 * @return the uuid of this timesheet approval
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this timesheet approval.
	 *
	 * @param uuid the uuid of this timesheet approval
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the timesheet approval ID of this timesheet approval.
	 *
	 * @return the timesheet approval ID of this timesheet approval
	 */
	public long getTimesheetApprovalId();

	/**
	 * Sets the timesheet approval ID of this timesheet approval.
	 *
	 * @param timesheetApprovalId the timesheet approval ID of this timesheet approval
	 */
	public void setTimesheetApprovalId(long timesheetApprovalId);

	/**
	 * Returns the group ID of this timesheet approval.
	 *
	 * @return the group ID of this timesheet approval
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this timesheet approval.
	 *
	 * @param groupId the group ID of this timesheet approval
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the timesheet ID of this timesheet approval.
	 *
	 * @return the timesheet ID of this timesheet approval
	 */
	public long getTimesheetId();

	/**
	 * Sets the timesheet ID of this timesheet approval.
	 *
	 * @param timesheetId the timesheet ID of this timesheet approval
	 */
	public void setTimesheetId(long timesheetId);

	/**
	 * Returns the company ID of this timesheet approval.
	 *
	 * @return the company ID of this timesheet approval
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this timesheet approval.
	 *
	 * @param companyId the company ID of this timesheet approval
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this timesheet approval.
	 *
	 * @return the user ID of this timesheet approval
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this timesheet approval.
	 *
	 * @param userId the user ID of this timesheet approval
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this timesheet approval.
	 *
	 * @return the user uuid of this timesheet approval
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this timesheet approval.
	 *
	 * @param userUuid the user uuid of this timesheet approval
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this timesheet approval.
	 *
	 * @return the user name of this timesheet approval
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this timesheet approval.
	 *
	 * @param userName the user name of this timesheet approval
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this timesheet approval.
	 *
	 * @return the create date of this timesheet approval
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this timesheet approval.
	 *
	 * @param createDate the create date of this timesheet approval
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this timesheet approval.
	 *
	 * @return the modified date of this timesheet approval
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this timesheet approval.
	 *
	 * @param modifiedDate the modified date of this timesheet approval
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this timesheet approval.
	 *
	 * @return the status of this timesheet approval
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this timesheet approval.
	 *
	 * @param status the status of this timesheet approval
	 */
	public void setStatus(String status);

	/**
	 * Returns the comment of this timesheet approval.
	 *
	 * @return the comment of this timesheet approval
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this timesheet approval.
	 *
	 * @param comment the comment of this timesheet approval
	 */
	public void setComment(String comment);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TimesheetApproval timesheetApproval);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TimesheetApproval> toCacheModel();

	@Override
	public TimesheetApproval toEscapedModel();

	@Override
	public TimesheetApproval toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}