/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gs.hack.timesheets.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.gs.hack.timesheets.model.TimesheetApproval;
import com.liferay.gs.hack.timesheets.model.TimesheetApprovalModel;
import com.liferay.gs.hack.timesheets.model.TimesheetApprovalSoap;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TimesheetApproval service. Represents a row in the &quot;TS_TimesheetApproval&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TimesheetApprovalModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TimesheetApprovalImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TimesheetApprovalImpl
 * @see TimesheetApproval
 * @see TimesheetApprovalModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TimesheetApprovalModelImpl extends BaseModelImpl<TimesheetApproval>
	implements TimesheetApprovalModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a timesheet approval model instance should use the {@link TimesheetApproval} interface instead.
	 */
	public static final String TABLE_NAME = "TS_TimesheetApproval";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "timesheetApprovalId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "timesheetId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "status", Types.VARCHAR },
			{ "comment_", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("timesheetApprovalId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("timesheetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("comment_", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table TS_TimesheetApproval (uuid_ VARCHAR(75) null,timesheetApprovalId LONG not null primary key,groupId LONG,timesheetId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status VARCHAR(75) null,comment_ VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table TS_TimesheetApproval";
	public static final String ORDER_BY_JPQL = " ORDER BY timesheetApproval.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TS_TimesheetApproval.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.gs.hack.timesheets.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.gs.hack.timesheets.model.TimesheetApproval"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.gs.hack.timesheets.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.gs.hack.timesheets.model.TimesheetApproval"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.gs.hack.timesheets.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.gs.hack.timesheets.model.TimesheetApproval"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long TIMESHEETID_COLUMN_BITMASK = 4L;
	public static final long UUID_COLUMN_BITMASK = 8L;
	public static final long CREATEDATE_COLUMN_BITMASK = 16L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TimesheetApproval toModel(TimesheetApprovalSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TimesheetApproval model = new TimesheetApprovalImpl();

		model.setUuid(soapModel.getUuid());
		model.setTimesheetApprovalId(soapModel.getTimesheetApprovalId());
		model.setGroupId(soapModel.getGroupId());
		model.setTimesheetId(soapModel.getTimesheetId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setComment(soapModel.getComment());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TimesheetApproval> toModels(
		TimesheetApprovalSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TimesheetApproval> models = new ArrayList<TimesheetApproval>(soapModels.length);

		for (TimesheetApprovalSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.gs.hack.timesheets.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.gs.hack.timesheets.model.TimesheetApproval"));

	public TimesheetApprovalModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _timesheetApprovalId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTimesheetApprovalId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _timesheetApprovalId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TimesheetApproval.class;
	}

	@Override
	public String getModelClassName() {
		return TimesheetApproval.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("timesheetApprovalId", getTimesheetApprovalId());
		attributes.put("groupId", getGroupId());
		attributes.put("timesheetId", getTimesheetId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("status", getStatus());
		attributes.put("comment", getComment());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long timesheetApprovalId = (Long)attributes.get("timesheetApprovalId");

		if (timesheetApprovalId != null) {
			setTimesheetApprovalId(timesheetApprovalId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long timesheetId = (Long)attributes.get("timesheetId");

		if (timesheetId != null) {
			setTimesheetId(timesheetId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		String comment = (String)attributes.get("comment");

		if (comment != null) {
			setComment(comment);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getTimesheetApprovalId() {
		return _timesheetApprovalId;
	}

	@Override
	public void setTimesheetApprovalId(long timesheetApprovalId) {
		_timesheetApprovalId = timesheetApprovalId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getTimesheetId() {
		return _timesheetId;
	}

	@Override
	public void setTimesheetId(long timesheetId) {
		_columnBitmask |= TIMESHEETID_COLUMN_BITMASK;

		if (!_setOriginalTimesheetId) {
			_setOriginalTimesheetId = true;

			_originalTimesheetId = _timesheetId;
		}

		_timesheetId = timesheetId;
	}

	public long getOriginalTimesheetId() {
		return _originalTimesheetId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@JSON
	@Override
	public String getComment() {
		if (_comment == null) {
			return StringPool.BLANK;
		}
		else {
			return _comment;
		}
	}

	@Override
	public void setComment(String comment) {
		_comment = comment;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				TimesheetApproval.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			TimesheetApproval.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TimesheetApproval toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TimesheetApproval)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TimesheetApprovalImpl timesheetApprovalImpl = new TimesheetApprovalImpl();

		timesheetApprovalImpl.setUuid(getUuid());
		timesheetApprovalImpl.setTimesheetApprovalId(getTimesheetApprovalId());
		timesheetApprovalImpl.setGroupId(getGroupId());
		timesheetApprovalImpl.setTimesheetId(getTimesheetId());
		timesheetApprovalImpl.setCompanyId(getCompanyId());
		timesheetApprovalImpl.setUserId(getUserId());
		timesheetApprovalImpl.setUserName(getUserName());
		timesheetApprovalImpl.setCreateDate(getCreateDate());
		timesheetApprovalImpl.setModifiedDate(getModifiedDate());
		timesheetApprovalImpl.setStatus(getStatus());
		timesheetApprovalImpl.setComment(getComment());

		timesheetApprovalImpl.resetOriginalValues();

		return timesheetApprovalImpl;
	}

	@Override
	public int compareTo(TimesheetApproval timesheetApproval) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				timesheetApproval.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TimesheetApproval)) {
			return false;
		}

		TimesheetApproval timesheetApproval = (TimesheetApproval)obj;

		long primaryKey = timesheetApproval.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TimesheetApprovalModelImpl timesheetApprovalModelImpl = this;

		timesheetApprovalModelImpl._originalUuid = timesheetApprovalModelImpl._uuid;

		timesheetApprovalModelImpl._originalGroupId = timesheetApprovalModelImpl._groupId;

		timesheetApprovalModelImpl._setOriginalGroupId = false;

		timesheetApprovalModelImpl._originalTimesheetId = timesheetApprovalModelImpl._timesheetId;

		timesheetApprovalModelImpl._setOriginalTimesheetId = false;

		timesheetApprovalModelImpl._originalCompanyId = timesheetApprovalModelImpl._companyId;

		timesheetApprovalModelImpl._setOriginalCompanyId = false;

		timesheetApprovalModelImpl._setModifiedDate = false;

		timesheetApprovalModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TimesheetApproval> toCacheModel() {
		TimesheetApprovalCacheModel timesheetApprovalCacheModel = new TimesheetApprovalCacheModel();

		timesheetApprovalCacheModel.uuid = getUuid();

		String uuid = timesheetApprovalCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			timesheetApprovalCacheModel.uuid = null;
		}

		timesheetApprovalCacheModel.timesheetApprovalId = getTimesheetApprovalId();

		timesheetApprovalCacheModel.groupId = getGroupId();

		timesheetApprovalCacheModel.timesheetId = getTimesheetId();

		timesheetApprovalCacheModel.companyId = getCompanyId();

		timesheetApprovalCacheModel.userId = getUserId();

		timesheetApprovalCacheModel.userName = getUserName();

		String userName = timesheetApprovalCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			timesheetApprovalCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			timesheetApprovalCacheModel.createDate = createDate.getTime();
		}
		else {
			timesheetApprovalCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			timesheetApprovalCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			timesheetApprovalCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		timesheetApprovalCacheModel.status = getStatus();

		String status = timesheetApprovalCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			timesheetApprovalCacheModel.status = null;
		}

		timesheetApprovalCacheModel.comment = getComment();

		String comment = timesheetApprovalCacheModel.comment;

		if ((comment != null) && (comment.length() == 0)) {
			timesheetApprovalCacheModel.comment = null;
		}

		return timesheetApprovalCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", timesheetApprovalId=");
		sb.append(getTimesheetApprovalId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", timesheetId=");
		sb.append(getTimesheetId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", comment=");
		sb.append(getComment());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.liferay.gs.hack.timesheets.model.TimesheetApproval");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>timesheetApprovalId</column-name><column-value><![CDATA[");
		sb.append(getTimesheetApprovalId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>timesheetId</column-name><column-value><![CDATA[");
		sb.append(getTimesheetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>comment</column-name><column-value><![CDATA[");
		sb.append(getComment());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = TimesheetApproval.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			TimesheetApproval.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _timesheetApprovalId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _timesheetId;
	private long _originalTimesheetId;
	private boolean _setOriginalTimesheetId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _status;
	private String _comment;
	private long _columnBitmask;
	private TimesheetApproval _escapedModel;
}