/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gs.hack.timesheets.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.gs.hack.timesheets.model.TimesheetTask;
import com.liferay.gs.hack.timesheets.model.TimesheetTaskModel;
import com.liferay.gs.hack.timesheets.model.TimesheetTaskSoap;
import com.liferay.gs.hack.timesheets.service.persistence.TimesheetTaskPK;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TimesheetTask service. Represents a row in the &quot;TS_TimesheetTask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TimesheetTaskModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TimesheetTaskImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TimesheetTaskImpl
 * @see TimesheetTask
 * @see TimesheetTaskModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TimesheetTaskModelImpl extends BaseModelImpl<TimesheetTask>
	implements TimesheetTaskModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a timesheet task model instance should use the {@link TimesheetTask} interface instead.
	 */
	public static final String TABLE_NAME = "TS_TimesheetTask";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "timesheetTaskId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "timesheetId", Types.BIGINT },
			{ "projectTaskId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userName", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "billable", Types.BOOLEAN }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("timesheetTaskId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("timesheetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("projectTaskId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("billable", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE = "create table TS_TimesheetTask (uuid_ VARCHAR(75) null,timesheetTaskId LONG not null,groupId LONG,timesheetId LONG not null,projectTaskId LONG not null,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,billable BOOLEAN,primary key (timesheetTaskId, timesheetId, projectTaskId))";
	public static final String TABLE_SQL_DROP = "drop table TS_TimesheetTask";
	public static final String ORDER_BY_JPQL = " ORDER BY timesheetTask.createDate ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TS_TimesheetTask.createDate ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.gs.hack.timesheets.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.liferay.gs.hack.timesheets.model.TimesheetTask"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.gs.hack.timesheets.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.liferay.gs.hack.timesheets.model.TimesheetTask"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.gs.hack.timesheets.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.liferay.gs.hack.timesheets.model.TimesheetTask"),
			true);
	public static final long COMPANYID_COLUMN_BITMASK = 1L;
	public static final long GROUPID_COLUMN_BITMASK = 2L;
	public static final long PROJECTTASKID_COLUMN_BITMASK = 4L;
	public static final long TIMESHEETID_COLUMN_BITMASK = 8L;
	public static final long UUID_COLUMN_BITMASK = 16L;
	public static final long CREATEDATE_COLUMN_BITMASK = 32L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TimesheetTask toModel(TimesheetTaskSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TimesheetTask model = new TimesheetTaskImpl();

		model.setUuid(soapModel.getUuid());
		model.setTimesheetTaskId(soapModel.getTimesheetTaskId());
		model.setGroupId(soapModel.getGroupId());
		model.setTimesheetId(soapModel.getTimesheetId());
		model.setProjectTaskId(soapModel.getProjectTaskId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setBillable(soapModel.getBillable());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TimesheetTask> toModels(TimesheetTaskSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TimesheetTask> models = new ArrayList<TimesheetTask>(soapModels.length);

		for (TimesheetTaskSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.gs.hack.timesheets.service.util.ServiceProps.get(
				"lock.expiration.time.com.liferay.gs.hack.timesheets.model.TimesheetTask"));

	public TimesheetTaskModelImpl() {
	}

	@Override
	public TimesheetTaskPK getPrimaryKey() {
		return new TimesheetTaskPK(_timesheetTaskId, _timesheetId,
			_projectTaskId);
	}

	@Override
	public void setPrimaryKey(TimesheetTaskPK primaryKey) {
		setTimesheetTaskId(primaryKey.timesheetTaskId);
		setTimesheetId(primaryKey.timesheetId);
		setProjectTaskId(primaryKey.projectTaskId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new TimesheetTaskPK(_timesheetTaskId, _timesheetId,
			_projectTaskId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((TimesheetTaskPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return TimesheetTask.class;
	}

	@Override
	public String getModelClassName() {
		return TimesheetTask.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("timesheetTaskId", getTimesheetTaskId());
		attributes.put("groupId", getGroupId());
		attributes.put("timesheetId", getTimesheetId());
		attributes.put("projectTaskId", getProjectTaskId());
		attributes.put("companyId", getCompanyId());
		attributes.put("userId", getUserId());
		attributes.put("userName", getUserName());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("billable", getBillable());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long timesheetTaskId = (Long)attributes.get("timesheetTaskId");

		if (timesheetTaskId != null) {
			setTimesheetTaskId(timesheetTaskId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long timesheetId = (Long)attributes.get("timesheetId");

		if (timesheetId != null) {
			setTimesheetId(timesheetId);
		}

		Long projectTaskId = (Long)attributes.get("projectTaskId");

		if (projectTaskId != null) {
			setProjectTaskId(projectTaskId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		Boolean billable = (Boolean)attributes.get("billable");

		if (billable != null) {
			setBillable(billable);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getTimesheetTaskId() {
		return _timesheetTaskId;
	}

	@Override
	public void setTimesheetTaskId(long timesheetTaskId) {
		_timesheetTaskId = timesheetTaskId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getTimesheetId() {
		return _timesheetId;
	}

	@Override
	public void setTimesheetId(long timesheetId) {
		_columnBitmask |= TIMESHEETID_COLUMN_BITMASK;

		if (!_setOriginalTimesheetId) {
			_setOriginalTimesheetId = true;

			_originalTimesheetId = _timesheetId;
		}

		_timesheetId = timesheetId;
	}

	public long getOriginalTimesheetId() {
		return _originalTimesheetId;
	}

	@JSON
	@Override
	public long getProjectTaskId() {
		return _projectTaskId;
	}

	@Override
	public void setProjectTaskId(long projectTaskId) {
		_columnBitmask |= PROJECTTASKID_COLUMN_BITMASK;

		if (!_setOriginalProjectTaskId) {
			_setOriginalProjectTaskId = true;

			_originalProjectTaskId = _projectTaskId;
		}

		_projectTaskId = projectTaskId;
	}

	public long getOriginalProjectTaskId() {
		return _originalProjectTaskId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return StringPool.BLANK;
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public boolean getBillable() {
		return _billable;
	}

	@JSON
	@Override
	public boolean isBillable() {
		return _billable;
	}

	@Override
	public void setBillable(boolean billable) {
		_billable = billable;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(PortalUtil.getClassNameId(
				TimesheetTask.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public TimesheetTask toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TimesheetTask)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TimesheetTaskImpl timesheetTaskImpl = new TimesheetTaskImpl();

		timesheetTaskImpl.setUuid(getUuid());
		timesheetTaskImpl.setTimesheetTaskId(getTimesheetTaskId());
		timesheetTaskImpl.setGroupId(getGroupId());
		timesheetTaskImpl.setTimesheetId(getTimesheetId());
		timesheetTaskImpl.setProjectTaskId(getProjectTaskId());
		timesheetTaskImpl.setCompanyId(getCompanyId());
		timesheetTaskImpl.setUserId(getUserId());
		timesheetTaskImpl.setUserName(getUserName());
		timesheetTaskImpl.setCreateDate(getCreateDate());
		timesheetTaskImpl.setModifiedDate(getModifiedDate());
		timesheetTaskImpl.setBillable(getBillable());

		timesheetTaskImpl.resetOriginalValues();

		return timesheetTaskImpl;
	}

	@Override
	public int compareTo(TimesheetTask timesheetTask) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				timesheetTask.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TimesheetTask)) {
			return false;
		}

		TimesheetTask timesheetTask = (TimesheetTask)obj;

		TimesheetTaskPK primaryKey = timesheetTask.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		TimesheetTaskModelImpl timesheetTaskModelImpl = this;

		timesheetTaskModelImpl._originalUuid = timesheetTaskModelImpl._uuid;

		timesheetTaskModelImpl._originalGroupId = timesheetTaskModelImpl._groupId;

		timesheetTaskModelImpl._setOriginalGroupId = false;

		timesheetTaskModelImpl._originalTimesheetId = timesheetTaskModelImpl._timesheetId;

		timesheetTaskModelImpl._setOriginalTimesheetId = false;

		timesheetTaskModelImpl._originalProjectTaskId = timesheetTaskModelImpl._projectTaskId;

		timesheetTaskModelImpl._setOriginalProjectTaskId = false;

		timesheetTaskModelImpl._originalCompanyId = timesheetTaskModelImpl._companyId;

		timesheetTaskModelImpl._setOriginalCompanyId = false;

		timesheetTaskModelImpl._setModifiedDate = false;

		timesheetTaskModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<TimesheetTask> toCacheModel() {
		TimesheetTaskCacheModel timesheetTaskCacheModel = new TimesheetTaskCacheModel();

		timesheetTaskCacheModel.timesheetTaskPK = getPrimaryKey();

		timesheetTaskCacheModel.uuid = getUuid();

		String uuid = timesheetTaskCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			timesheetTaskCacheModel.uuid = null;
		}

		timesheetTaskCacheModel.timesheetTaskId = getTimesheetTaskId();

		timesheetTaskCacheModel.groupId = getGroupId();

		timesheetTaskCacheModel.timesheetId = getTimesheetId();

		timesheetTaskCacheModel.projectTaskId = getProjectTaskId();

		timesheetTaskCacheModel.companyId = getCompanyId();

		timesheetTaskCacheModel.userId = getUserId();

		timesheetTaskCacheModel.userName = getUserName();

		String userName = timesheetTaskCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			timesheetTaskCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			timesheetTaskCacheModel.createDate = createDate.getTime();
		}
		else {
			timesheetTaskCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			timesheetTaskCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			timesheetTaskCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		timesheetTaskCacheModel.billable = getBillable();

		return timesheetTaskCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(23);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", timesheetTaskId=");
		sb.append(getTimesheetTaskId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", timesheetId=");
		sb.append(getTimesheetId());
		sb.append(", projectTaskId=");
		sb.append(getProjectTaskId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", billable=");
		sb.append(getBillable());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(37);

		sb.append("<model><model-name>");
		sb.append("com.liferay.gs.hack.timesheets.model.TimesheetTask");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>timesheetTaskId</column-name><column-value><![CDATA[");
		sb.append(getTimesheetTaskId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>timesheetId</column-name><column-value><![CDATA[");
		sb.append(getTimesheetId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>projectTaskId</column-name><column-value><![CDATA[");
		sb.append(getProjectTaskId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>billable</column-name><column-value><![CDATA[");
		sb.append(getBillable());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = TimesheetTask.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			TimesheetTask.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _timesheetTaskId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _timesheetId;
	private long _originalTimesheetId;
	private boolean _setOriginalTimesheetId;
	private long _projectTaskId;
	private long _originalProjectTaskId;
	private boolean _setOriginalProjectTaskId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private boolean _billable;
	private long _columnBitmask;
	private TimesheetTask _escapedModel;
}