/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gs.hack.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ProjectUser service. Represents a row in the &quot;GS_ProjectUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.gs.hack.model.impl.ProjectUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.gs.hack.model.impl.ProjectUserImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectUser
 * @see com.liferay.gs.hack.model.impl.ProjectUserImpl
 * @see com.liferay.gs.hack.model.impl.ProjectUserModelImpl
 * @generated
 */
@ProviderType
public interface ProjectUserModel extends BaseModel<ProjectUser>, GroupedModel,
	ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project user model instance should use the {@link ProjectUser} interface instead.
	 */

	/**
	 * Returns the primary key of this project user.
	 *
	 * @return the primary key of this project user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project user.
	 *
	 * @param primaryKey the primary key of this project user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project user.
	 *
	 * @return the uuid of this project user
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this project user.
	 *
	 * @param uuid the uuid of this project user
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the project user ID of this project user.
	 *
	 * @return the project user ID of this project user
	 */
	public long getProjectUserId();

	/**
	 * Sets the project user ID of this project user.
	 *
	 * @param projectUserId the project user ID of this project user
	 */
	public void setProjectUserId(long projectUserId);

	/**
	 * Returns the project user uuid of this project user.
	 *
	 * @return the project user uuid of this project user
	 */
	public String getProjectUserUuid();

	/**
	 * Sets the project user uuid of this project user.
	 *
	 * @param projectUserUuid the project user uuid of this project user
	 */
	public void setProjectUserUuid(String projectUserUuid);

	/**
	 * Returns the group ID of this project user.
	 *
	 * @return the group ID of this project user
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this project user.
	 *
	 * @param groupId the group ID of this project user
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this project user.
	 *
	 * @return the company ID of this project user
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this project user.
	 *
	 * @param companyId the company ID of this project user
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this project user.
	 *
	 * @return the user ID of this project user
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this project user.
	 *
	 * @param userId the user ID of this project user
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this project user.
	 *
	 * @return the user uuid of this project user
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this project user.
	 *
	 * @param userUuid the user uuid of this project user
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this project user.
	 *
	 * @return the user name of this project user
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this project user.
	 *
	 * @param userName the user name of this project user
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this project user.
	 *
	 * @return the create date of this project user
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this project user.
	 *
	 * @param createDate the create date of this project user
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this project user.
	 *
	 * @return the modified date of this project user
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this project user.
	 *
	 * @param modifiedDate the modified date of this project user
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the project ID of this project user.
	 *
	 * @return the project ID of this project user
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this project user.
	 *
	 * @param projectId the project ID of this project user
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the employee ID of this project user.
	 *
	 * @return the employee ID of this project user
	 */
	public long getEmployeeId();

	/**
	 * Sets the employee ID of this project user.
	 *
	 * @param employeeId the employee ID of this project user
	 */
	public void setEmployeeId(long employeeId);

	/**
	 * Returns the role ID of this project user.
	 *
	 * @return the role ID of this project user
	 */
	public long getRoleId();

	/**
	 * Sets the role ID of this project user.
	 *
	 * @param roleId the role ID of this project user
	 */
	public void setRoleId(long roleId);

	/**
	 * Returns the bill rate of this project user.
	 *
	 * @return the bill rate of this project user
	 */
	public double getBillRate();

	/**
	 * Sets the bill rate of this project user.
	 *
	 * @param billRate the bill rate of this project user
	 */
	public void setBillRate(double billRate);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ProjectUser projectUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProjectUser> toCacheModel();

	@Override
	public ProjectUser toEscapedModel();

	@Override
	public ProjectUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}