/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gs.hack.timesheets.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.gs.hack.timesheets.service.persistence.TimesheetTaskDurationPK;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TimesheetTaskDuration service. Represents a row in the &quot;TS_TimesheetTaskDuration&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.liferay.gs.hack.timesheets.model.impl.TimesheetTaskDurationModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.liferay.gs.hack.timesheets.model.impl.TimesheetTaskDurationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TimesheetTaskDuration
 * @see com.liferay.gs.hack.timesheets.model.impl.TimesheetTaskDurationImpl
 * @see com.liferay.gs.hack.timesheets.model.impl.TimesheetTaskDurationModelImpl
 * @generated
 */
@ProviderType
public interface TimesheetTaskDurationModel extends BaseModel<TimesheetTaskDuration>,
	GroupedModel, ShardedModel, StagedAuditedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a timesheet task duration model instance should use the {@link TimesheetTaskDuration} interface instead.
	 */

	/**
	 * Returns the primary key of this timesheet task duration.
	 *
	 * @return the primary key of this timesheet task duration
	 */
	public TimesheetTaskDurationPK getPrimaryKey();

	/**
	 * Sets the primary key of this timesheet task duration.
	 *
	 * @param primaryKey the primary key of this timesheet task duration
	 */
	public void setPrimaryKey(TimesheetTaskDurationPK primaryKey);

	/**
	 * Returns the uuid of this timesheet task duration.
	 *
	 * @return the uuid of this timesheet task duration
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this timesheet task duration.
	 *
	 * @param uuid the uuid of this timesheet task duration
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the timesheet task duration ID of this timesheet task duration.
	 *
	 * @return the timesheet task duration ID of this timesheet task duration
	 */
	public long getTimesheetTaskDurationId();

	/**
	 * Sets the timesheet task duration ID of this timesheet task duration.
	 *
	 * @param timesheetTaskDurationId the timesheet task duration ID of this timesheet task duration
	 */
	public void setTimesheetTaskDurationId(long timesheetTaskDurationId);

	/**
	 * Returns the group ID of this timesheet task duration.
	 *
	 * @return the group ID of this timesheet task duration
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this timesheet task duration.
	 *
	 * @param groupId the group ID of this timesheet task duration
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the timesheet ID of this timesheet task duration.
	 *
	 * @return the timesheet ID of this timesheet task duration
	 */
	public long getTimesheetId();

	/**
	 * Sets the timesheet ID of this timesheet task duration.
	 *
	 * @param timesheetId the timesheet ID of this timesheet task duration
	 */
	public void setTimesheetId(long timesheetId);

	/**
	 * Returns the timesheet task ID of this timesheet task duration.
	 *
	 * @return the timesheet task ID of this timesheet task duration
	 */
	public long getTimesheetTaskId();

	/**
	 * Sets the timesheet task ID of this timesheet task duration.
	 *
	 * @param timesheetTaskId the timesheet task ID of this timesheet task duration
	 */
	public void setTimesheetTaskId(long timesheetTaskId);

	/**
	 * Returns the company ID of this timesheet task duration.
	 *
	 * @return the company ID of this timesheet task duration
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this timesheet task duration.
	 *
	 * @param companyId the company ID of this timesheet task duration
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this timesheet task duration.
	 *
	 * @return the user ID of this timesheet task duration
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this timesheet task duration.
	 *
	 * @param userId the user ID of this timesheet task duration
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this timesheet task duration.
	 *
	 * @return the user uuid of this timesheet task duration
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this timesheet task duration.
	 *
	 * @param userUuid the user uuid of this timesheet task duration
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this timesheet task duration.
	 *
	 * @return the user name of this timesheet task duration
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this timesheet task duration.
	 *
	 * @param userName the user name of this timesheet task duration
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this timesheet task duration.
	 *
	 * @return the create date of this timesheet task duration
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this timesheet task duration.
	 *
	 * @param createDate the create date of this timesheet task duration
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this timesheet task duration.
	 *
	 * @return the modified date of this timesheet task duration
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this timesheet task duration.
	 *
	 * @param modifiedDate the modified date of this timesheet task duration
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the duration of this timesheet task duration.
	 *
	 * @return the duration of this timesheet task duration
	 */
	public double getDuration();

	/**
	 * Sets the duration of this timesheet task duration.
	 *
	 * @param duration the duration of this timesheet task duration
	 */
	public void setDuration(double duration);

	/**
	 * Returns the comment of this timesheet task duration.
	 *
	 * @return the comment of this timesheet task duration
	 */
	@AutoEscape
	public String getComment();

	/**
	 * Sets the comment of this timesheet task duration.
	 *
	 * @param comment the comment of this timesheet task duration
	 */
	public void setComment(String comment);

	/**
	 * Returns the day of this timesheet task duration.
	 *
	 * @return the day of this timesheet task duration
	 */
	public int getDay();

	/**
	 * Sets the day of this timesheet task duration.
	 *
	 * @param day the day of this timesheet task duration
	 */
	public void setDay(int day);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TimesheetTaskDuration timesheetTaskDuration);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TimesheetTaskDuration> toCacheModel();

	@Override
	public TimesheetTaskDuration toEscapedModel();

	@Override
	public TimesheetTaskDuration toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}